spring:
  datasource:
    url: http://172.30.240.1:8082/login.do?jsessionid=0a301f6b156e5ad9bbaa45317535bbf4
    username: root
    password: root
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html